### ISSUE TITLE
steampipe and linux update issues

### ISSUE THREAD

**Issue by pierow** [unknownworlds/NS#6]
The recent engine update introduced some issues to the game that have mostly since been fixed but there are a few remaining like the gorge's view rotates when he drops a structure from the popup menu, repeated leaping and firing, and new frame rate peaks for max fire rates.  The remaining community members still downgrade to an older version due to major issues that have mostly been fixed, but others still likely remain and need further play to test.

**Comment by archienz** [comment]
I'd like to see that someone actually fixes these issues, there are more that need to be looked at. Anyone actively working on any in-house upgrades?

**Comment by fmoraw** [comment]
I have ported NS to linux but there are still some minor issues. Check my repository for more information.

**Comment by archienz** [comment]
@fmoraw Wow this is awesome, i'm going to give it a try this weekend :dancer: 

Thank you so much! Also i was just wondering if you are implementing any of the fixes that the Valve update of half-life broke? would be cool to fix that!

Also didn't there also exist a linux version of the dll files that came with it?

**Comment by fmoraw** [comment]
@archienz I merged the files from Valve's half-life code on github with the NS source code. I think that should fix the problems which were caused by the steam-update. There wasn't any linux client until now. But you could do a playtest and report the issues back.

**Comment by pierow** [comment]
@fmoraw I tested out the new dlls and was able to join existing 3.2 servers and the popup menu issues seem to be partially resolved.  Using the menu no longer rotates your view, but the cursor location is now memorized from the last time you open the menu, instead of beginning at the center as intended.

I couldn't start a listen server. The console gave me this message:

Adding:  ns/dlls\ns.dll
LoadLibrary failed on c:\program files (x86)\steam\steamapps\common\half-life\ns\dlls\ns.dll (126)
BAD:   -1:svc_bad
Wrote erroneous message to buffer.dat
Host_Error: Couldn't get DLL API from c:\program files (x86)\steam\steamapps\common\half-life\ns\dlls\ns.dll!

**Comment by archienz** [comment]
I haven't done a playtest yet(sorry for getting back to you after so long) i'm setting up my linux machine in the next week to do some testing, i'll prompt you when that is ready.

Thanks!

**Comment by fmoraw** [comment]
@pierow Thank you. I will look into it when I have some spare time.
@archienz That is good to hear!
... and if you know someone who could do a build for osx and test it, that would be great.
